version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: eventplanner
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./eventplanner.sql:/docker-entrypoint-initdb.d/eventplanner.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
